export const SUBMIT_LOGIN = "SUBMIT_LOGIN";
export const SUBMIT_LOGIN_ERROR = "SUBMIT_LOGIN_ERROR";
export const SUBMIT_LOGIN_SUCCESS = "SUBMIT_LOGIN_SUCCESS";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";

export const SUBMIT_REGISTER = "SUBMIT_REGISTER";
export const SUBMIT_REGISTER_ERROR = "SUBMIT_REGISTER_ERROR";
export const SUBMIT_REGISTER_SUCCESS = "SUBMIT_REGISTER_SUCCESS";

export const FETCH_USER_DATA = "FETCH_USER_DATA";
export const SET_USER_DATA = "SET_USER_DATA";
export const FETCH_USER_DATA_ERROR = "FETCH_USER_DATA_ERROR";

export const FETCH_MEALS = "FETCH_MEALS";
export const FETCH_MEALS_SUCCESS = "FETCH_MEALS_SUCCESS";
export const FETCH_MEALS_ERROR = "FETCH_MEALS_ERROR";

export const SUBMIT_ADD_MEAL = "SUBMIT_ADD_MEAL";
export const SUBMIT_ADD_MEAL_SUCCESS = "SUBMIT_ADD_MEAL_SUCCESS";
export const SUBMIT_ADD_MEAL_ERROR = "SUBMIT_ADD_MEAL_ERROR";

export const SUBMIT_EDIT_MEAL = "SUBMIT_EDIT_MEAL";
export const SUBMIT_EDIT_MEAL_SUCCESS = "SUBMIT_EDIT_MEAL_SUCCESS";
export const SUBMIT_EDIT_MEAL_ERROR = "SUBMIT_EDIT_MEAL_ERROR";
