export const SUBMIT_LOGIN = "SUBMIT_LOGIN";
export const SUBMIT_LOGIN_ERROR = "SUBMIT_LOGIN_ERROR";
export const SUBMIT_LOGIN_SUCCESS = "SUBMIT_LOGIN_SUCCESS";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";

export const SUBMIT_REGISTER = "SUBMIT_REGISTER";
export const SUBMIT_REGISTER_ERROR = "SUBMIT_REGISTER_ERROR";
export const SUBMIT_REGISTER_SUCCESS = "SUBMIT_REGISTER_SUCCESS";

export const FETCH_USER_DATA = "FETCH_USER_DATA";
export const SET_USER_DATA = "SET_USER_DATA";
export const FETCH_USER_DATA_ERROR = "FETCH_USER_DATA_ERROR";

export const SUBMIT_UPDATE_USER = "SUBMIT_UPDATE_USER";
export const SUBMIT_UPDATE_USER_SUCCESS = "SUBMIT_UPDATE_USER_SUCCESS";
export const SUBMIT_UPDATE_USER_ERROR = "SUBMIT_UPDATE_USER_ERROR";

export const SUBMIT_UPDATE_PASSWORD = "SUBMIT_UPDATE_PASSWORD";
export const SUBMIT_UPDATE_PASSWORD_SUCCESS = "SUBMIT_UPDATE_PASSWORD_SUCCESS";
export const SUBMIT_UPDATE_PASSWORD_ERROR = "SUBMIT_UPDATE_PASSWORD_ERROR";

export const FETCH_MEALS = "FETCH_MEALS";
export const FETCH_MEALS_SUCCESS = "FETCH_MEALS_SUCCESS";
export const FETCH_MEALS_ERROR = "FETCH_MEALS_ERROR";

export const FETCH_MEALS_STATS = "FETCH_MEALS_STATS";
export const FETCH_MEALS_STATS_SUCCESS = "FETCH_MEALS_STATS_SUCCESS";
export const FETCH_MEALS_STATS_ERROR = "FETCH_MEALS_STATS_ERROR";

export const SUBMIT_ADD_MEAL = "SUBMIT_ADD_MEAL";
export const SUBMIT_ADD_MEAL_SUCCESS = "SUBMIT_ADD_MEAL_SUCCESS";
export const SUBMIT_ADD_MEAL_ERROR = "SUBMIT_ADD_MEAL_ERROR";

export const SUBMIT_DELETE_MEAL = "SUBMIT_DELETE_MEAL";
export const SUBMIT_DELETE_MEAL_SUCCESS = "SUBMIT_DELETE_MEAL_SUCCESS";
export const SUBMIT_DELETE_MEAL_ERROR = "SUBMIT_DELETE_MEAL_ERROR";

export const SUBMIT_EDIT_MEAL = "SUBMIT_EDIT_MEAL";
export const SUBMIT_EDIT_MEAL_SUCCESS = "SUBMIT_EDIT_MEAL_SUCCESS";
export const SUBMIT_EDIT_MEAL_ERROR = "SUBMIT_EDIT_MEAL_ERROR";

export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_ERROR = "FETCH_USERS_ERROR";

export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_ERROR = "DELETE_USER_ERROR";
